spring.application.name=E-Notes-Api-Service


spring.datasource.url=jdbc:mysql://localhost:3306/enotes
spring.datasource.username=root
spring.datasource.password=Skmania@1234

spring.jpa.hibernate.ddl-auto=none